import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReduxProvider from "./context/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
<<<<<<< HEAD
<<<<<<< Updated upstream
  title: 'Create Next App',
  description: 'Generated by create next app',
}
=======
  title: "Flower City Virtual Tours",
  description: "Web Development and Matterport Virtual Tours",
};
>>>>>>> Stashed changes
=======
  title: "Jobit",
  description: "Job finder for developers",
};
>>>>>>> 7b98615b5fda02850add607ecd94c1e0627ab197

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
